### ISSUE TITLE
Enable reliable publishing of event messages to Redis Streams

### ISSUE THREAD

**Issue by ghost** [absmach/magistrala#703] opened 2019-04-09 12:23 UTC
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

Currently there are mqtt adapter and bootstrap service publishing event messages to Redis Streams. Some of these events are status changes so it's very important to have them successfully published.
If the Redis Streams servers can not accept messages, the service/adapter should have a way to store those unpublished events and retry.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

Since the events notifying about status changes are important for having an accurate overview of the system, I think that this feature is a must have one.

**Comment by abay94** [comment] 2019-04-19 05:31
Hello! 
I need a help related to bootstrap service. There is bad request coming from the service, when i send post request to localhost:8200/things/configs, it responses *400* bad request. Which is malformed json but the body of request is the same as have to be, like
{
  "external_id" : "88:e9:fe:52:98:6e",
  "external_key":"0a:e9:fe:52:98:6e" ,
  "name":"some", 
  "channels":["d7804d0b-af47-430a-a453-4c52d53ca1ba"],
  "thing_id":"194f212e-81b6-4f66-a187-c2ed372c5923",
  "content": "config"
}

**Comment by drasko** [comment] 2019-09-25 19:17
@anovakovic01 @nmarcetic do you have any ideas how this can be implemented? I think this can be a `good-first-issue` if defined well.

**Comment by anovakovic01** [comment] 2019-09-25 19:22
@drasko as far as I can tell, this is a duplicate of #652.

**Comment by anovakovic01** [comment] 2019-09-25 19:27
@drasko I think that we need to solve #652 too. These two are related.

**Closed as completed** 2023-07-31 15:03 UTC
Labels: needs-comments
