### ISSUE TITLE
Mock services refactor

### ISSUE THREAD

**Issue by mteodor** [absmach/magistrala#1382] opened 2021-03-04 16:47 UTC
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No
2. Describe the feature you are requesting, as well as the possible use case(s) for it.
 we have several "different" mock implementations of services being used for testing in different services
```
-rw-rw-r-- 1 mirko mirko 1423 мар  4 15:13 ./readers/mocks/things.go
-rw-rw-r-- 1 mirko mirko 1854 мар  4 15:13 ./http/mocks/things.go
-rw-rw-r-- 1 mirko mirko 7643 мар  4 15:35 ./bootstrap/mocks/things.go
-rw-rw-r-- 1 mirko mirko 5948 мар  4 15:35 ./things/mocks/things.go
-rw-rw-r-- 1 mirko mirko 7643 мар  4 16:31 ./certs/mocks/things.go
```
we should create a common mock implementation and put it in one package

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
should-have

**Comment by dborovcanin** [comment] 2024-04-18 20:12
This is a duplicate of #1993.

**Closed as completed by dborovcanin** 2024-04-18 20:12 UTC
Labels: work-in-progress, wontfix, tests
