### ISSUE TITLE
Problem with installation from source

### ISSUE THREAD

**Issue by 2014siavash** [absmach/magistrala#102] opened 2017-09-26 05:32 UTC
Hi,
There is also some problems with installation from source as follows:

1- For message-writer and http-adaptor, we have the following error:

fatal: could not read Username for 'https://github.com': terminal prompts disabled.

I dont know how can I fix this. It should be mentioned that we have not this problem for mqtt-adaptor and everything is fine for this.

2- The go command cannot run with sudo, so we need to use 'chown' command to get the permission of making directories in your 'mainflux-install.sh' file.

---------------------------------------------------------------------------------------
siavash@ubuntu:~/Desktop/Mainflux2/mainflux/bin$ ./mainflux-install.sh 
./mainflux-install.sh: line 16: Manager: command not found
github.com/mainflux/message-writer (download)
cd .; git clone https://github.com/mainflux/message-writer /home/siavash/Desktop/Mainflux2/mainflux/bin/mainflux/go/src/github.com/mainflux/message-writer
Cloning into '/home/siavash/Desktop/Mainflux2/mainflux/bin/mainflux/go/src/github.com/mainflux/message-writer'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/mainflux/message-writer: exit status 128
github.com/mainflux/http-adapter (download)
cd .; git clone https://github.com/mainflux/http-adapter /home/siavash/Desktop/Mainflux2/mainflux/bin/mainflux/go/src/github.com/mainflux/http-adapter
Cloning into '/home/siavash/Desktop/Mainflux2/mainflux/bin/mainflux/go/src/github.com/mainflux/http-adapter'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/mainflux/http-adapter: exit status 128
fatal: destination path 'mqtt-adapter' already exists and is not an empty directory.

siavash@ubuntu:~/Desktop/Mainflux2/mainflux/bin$

**Comment by nmarcetic** [comment] 2017-09-26 11:23
@2014siavash This is similar to https://github.com/mainflux/mainflux/issues/98 as @drasko explained this is caused by transition to monorepo, which is not fully done yet. @drasko Can you please try to fix the script ?

**Comment by drasko** [comment] 2017-09-26 11:25
Yep, sure. Working on it now.

**Comment by drasko** [comment] 2017-09-27 22:21
Fixed by https://github.com/mainflux/mainflux/commit/f2aa007fabd34363b46ccf83edaebe53c3415cb6

**Closed as completed by drasko** 2017-09-27 22:21 UTC
Labels: bug
