### ISSUE TITLE
Benchmarking tool - timing results look too high

### ISSUE THREAD

**Issue by mteodor** [absmach/magistrala#949] opened 2019-11-13 11:54 UTC
Average time for message delivery seem it is too high, don't know if it is just displayed in wrong units.

**Comment by manuio** [comment] 2020-01-14 11:27
@mteodor any news about this one?

**Comment by mteodor** [comment] 2020-03-24 10:10
lets see if  mzbench tool satisfies benchmarking  and then decide if we need to address this

**Comment by blokovi** [comment] 2020-09-10 07:23
I didn't notice this issue while using mzbench, @mteodor can we close this?

**Comment by dborovcanin** [comment] 2023-03-01 09:14
Since we're not able to reproduce this one with other tools, and due to inactivity, I'm closing it.

**Closed as completed by dborovcanin** 2023-03-01 09:14 UTC
Labels: bug
